apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-dep-monitor
  namespace: myapp
  labels:
    release: monitoring
    app: app-dep
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: app-dep # must match your Service's labels
  namespaceSelector:
    matchNames:
      - myapp
  endpoints:
    - port: web # must match the named port in your Service
      path: /actuator/prometheus
      interval: 30s
